### ISSUE TITLE
Doesn't starts clot

### ISSUE THREAD

**Issue by schaumb** [merwin-asm/Clot#2]
**Describe the bug**

**To Reproduce**
1. pip install clot-terminal
2. clot
3. see error:

```
$ clot
xxxxx
<built-in method fileno of _io.TextIOWrapper object at 0x7fbe46b18ee0>
+++++
Traceback (most recent call last):
  File "/home/***/.local/bin/clot", line 5, in <module>
    from main import main
ImportError: cannot import name 'main' from 'main' (/home/***/.local/bin/main.py)
```

**Expected behavior**
Works

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3
 - Browser -
 - Version - 
 - Terminal: GNU bash, version 5.0.17(1)-release

**Comment by merwin-asm** [comment]
Its a bug from v 0.0.1 .. 
Which got fixed in v 0.0.1

Try installing again.
pip uninstall clot-terminal
pip install clot-terminal==0.0.2
